"use strict";


const ActionTypes = {
  ENTER_PIE_CHART_NAME: 'ENTER_PIE_CHART_NAME',
  ADD_PIE_SLICE: 'ADD_PIE_SLICE',
  // CHANGE_SLICE_NAME: 'CHANGE_SLICE_NAME',

  CHANGE_NAME_PIE: 'CHANGE_NAME_PIE',
  CHANGE_NAME_BAR: 'CHANGE_NAME_BAR',



  CREATE_SLICE: 'CREATE_SLICE',
  DELETE_SLICE: 'DELETE_SLICE',


  FETCH_BAR_DATA:'FETCH_BAR_DATA',
  SERVER_RESPONSE:'SERVER_RESPONSE',

  //bar
  CREATE_SERIES: 'CREATE_SERIES',
  CELL_CHANGED: 'CELL_CHANGED',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  DELETE_SERIES: 'DELETE_SERIES',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  UPDATE_COLOR:'UPDATE_COLOR'



};

export default ActionTypes;
